### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by ghost** [Lynnesbian/OCRbot#10]
Hello,

Many thanks for your work on this useful project.
I'm getting timeouts when I try to run reply.py:

```
Apr 08 18:43:01 ocr-bot01 systemd[1]: Started OCRbot reply manager.
Apr 08 18:43:02 ocr-bot01 python3[367]: Logging in...
Apr 08 18:43:02 ocr-bot01 python3[367]: Using Tesseract (sh)
Apr 08 18:43:02 ocr-bot01 python3[367]: Available languages: eng, fra
Apr 08 18:43:02 ocr-bot01 python3[367]: Starting OCRbot.
Apr 08 18:48:02 ocr-bot01 python3[367]: Traceback (most recent call last):
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
Apr 08 18:48:02 ocr-bot01 python3[367]:     six.raise_from(e, None)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "<string>", line 3, in raise_from
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
Apr 08 18:48:02 ocr-bot01 python3[367]:     httplib_response = conn.getresponse()
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
Apr 08 18:48:02 ocr-bot01 python3[367]:     response.begin()
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3.6/http/client.py", line 297, in begin
Apr 08 18:48:02 ocr-bot01 python3[367]:     version, status, reason = self._read_status()
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
Apr 08 18:48:02 ocr-bot01 python3[367]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3.6/socket.py", line 586, in readinto
Apr 08 18:48:02 ocr-bot01 python3[367]:     return self._sock.recv_into(b)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
Apr 08 18:48:02 ocr-bot01 python3[367]:     return self.read(nbytes, buffer)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3.6/ssl.py", line 874, in read
Apr 08 18:48:02 ocr-bot01 python3[367]:     return self._sslobj.read(len, buffer)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3.6/ssl.py", line 631, in read
Apr 08 18:48:02 ocr-bot01 python3[367]:     v = self._sslobj.read(len, buffer)
Apr 08 18:48:02 ocr-bot01 python3[367]: socket.timeout: The read operation timed out
Apr 08 18:48:02 ocr-bot01 python3[367]: During handling of the above exception, another exception occurred:
Apr 08 18:48:02 ocr-bot01 python3[367]: Traceback (most recent call last):
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
Apr 08 18:48:02 ocr-bot01 python3[367]:     timeout=timeout
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
Apr 08 18:48:02 ocr-bot01 python3[367]:     _stacktrace=sys.exc_info()[2])
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 357, in increment
Apr 08 18:48:02 ocr-bot01 python3[367]:     raise six.reraise(type(error), error, _stacktrace)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
Apr 08 18:48:02 ocr-bot01 python3[367]:     raise value
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
Apr 08 18:48:02 ocr-bot01 python3[367]:     chunked=chunked)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
Apr 08 18:48:02 ocr-bot01 python3[367]:     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
Apr 08 18:48:02 ocr-bot01 python3[367]:     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
Apr 08 18:48:02 ocr-bot01 python3[367]: urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='social.mental.af', port=443): Read timed out. (read timeout=300)
Apr 08 18:48:02 ocr-bot01 python3[367]: During handling of the above exception, another exception occurred:
Apr 08 18:48:02 ocr-bot01 python3[367]: Traceback (most recent call last):
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "reply.py", line 216, in <module>
Apr 08 18:48:02 ocr-bot01 python3[367]:     client.stream_user(rl) #go!
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-83>", line 2, in stream_user
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/mastodon/Mastodon.py", line 77, in wrapper
Apr 08 18:48:02 ocr-bot01 python3[367]:     return function(self, *args, **kwargs)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/mastodon/Mastodon.py", line 1987, in stream_user
Apr 08 18:48:02 ocr-bot01 python3[367]:     return self.__stream('/api/v1/streaming/user', listener, run_async=run_async, timeout=timeout, reconnect_async=reconnect_async, reconnect_async_wait_sec=reconnect_async_wait_sec)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/mastodon/Mastodon.py", line 2324, in __stream
Apr 08 18:48:02 ocr-bot01 python3[367]:     connection = connect_func()
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/mastodon/Mastodon.py", line 2319, in connect_func
Apr 08 18:48:02 ocr-bot01 python3[367]:     timeout=(self.request_timeout, timeout))
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 546, in get
Apr 08 18:48:02 ocr-bot01 python3[367]:     return self.request('GET', url, **kwargs)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
Apr 08 18:48:02 ocr-bot01 python3[367]:     resp = self.send(prep, **send_kwargs)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
Apr 08 18:48:02 ocr-bot01 python3[367]:     r = adapter.send(request, **kwargs)
Apr 08 18:48:02 ocr-bot01 python3[367]:   File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 529, in send
Apr 08 18:48:02 ocr-bot01 python3[367]:     raise ReadTimeout(e, request=request)
Apr 08 18:48:02 ocr-bot01 python3[367]: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='social.mental.af', port=443): Read timed out. (read timeout=300)
Apr 08 18:48:02 ocr-bot01 systemd[1]: ocr-bot.service: Main process exited, code=exited, status=1/FAILURE
Apr 08 18:48:02 ocr-bot01 systemd[1]: ocr-bot.service: Failed with result 'exit-code'.
```

I don't understand why those timeouts appears, do you have any clue?

**Comment by Lynnesbian** [comment]
hmm, there's a timeout of 300 seconds, and i assume your server doesn't take that long to respond, meaning that the issue is somewhere else. your instance loads fine in my browser, but there's evidently something stopping OCRbot from accessing it. i'm not really sure what, but i'll try to look into this.

**Comment by ghost** [comment]
@Lynnesbian thank your for your answer, I'll give it another try soon and keep you posted.

**Comment by ghost** [comment]
Hi,

Sorry for haven't gotten back to you sooner, I don't use or maintain a Mastodon instance anymore so I can't debug this furthermore.

I'll close this issue.
