### ISSUE TITLE
OCRbot broken after Mastodon 3.4.0 upgrade

### ISSUE THREAD

**Issue by LasersAreGreat** [Lynnesbian/OCRbot#35]
I had an instance of OCR bot running and then upgraded my Mastodon instance from 3.3.0 to 3.4.0. OCRbot immediately stopped working.  The Mastodon instance works fine, and other bots that do things like post RSS feeds are working fine.  Here is the error message I get:

$ /home/ocrbot/ocrbot/OCRbot/service.py
Logging in...
Using Tesseract (sh)
Available languages: eng
Starting OCRbot.
Traceback (most recent call last):
  File "/home/ocrbot/ocrbot/OCRbot/service.py", line 314, in <module>
    client.stream_user(rl) #go!
  File "/home/ocrbot/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ocrbot/.local/lib/python3.8/site-packages/mastodon/Mastodon.py", line 102, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ocrbot/.local/lib/python3.8/site-packages/mastodon/Mastodon.py", line 3110, in stream_user
    return self.__stream('/api/v1/streaming/user', listener, run_async=run_async, timeout=timeout, reconnect_async=reconnect_async, reconnect_async_wait_sec=reconnect_async_wait_sec)
  File "/home/ocrbot/.local/lib/python3.8/site-packages/mastodon/Mastodon.py", line 3626, in __stream
    connection = connect_func()            
  File "/home/ocrbot/.local/lib/python3.8/site-packages/mastodon/Mastodon.py", line 3553, in connect_func
    raise MastodonNetworkError("Could not connect to streaming server: %s" % connection.reason)
mastodon.Mastodon.MastodonNetworkError: Could not connect to streaming server: Internal Server Error

**Comment by nemobis** [comment]
Is this still current? https://fedi.lynnesbian.space/@OCRbot operates just fine with 3.5 and 4.0.
